modLoader = "javafml"
loaderVersion = "[2,)"
license = "Apache-2.0 & LGPL-2.1-only"
issueTrackerURL = "https://github.com/Jab125/convention-tags/issues"

[[mods]]
modId = "conventiontags"
version = "${version}"
displayName = "Convention tags"
authors = "Jab125"
displayURL = "https://github.com/Jab125/convention-tags"
description = '''
Convention tags for multiplatform mods.
'''

[[dependencies.conventiontags]]
modId = "neoforge"
mandatory = true
type="required"
versionRange = "[21.0.0-beta,22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.conventiontags]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"